SourceCode-code/Source_Batch_2

Github_sessions/Git_Cheat_sheet.txt
hey this is done to add cheat sheet
=> Adding cheat sheet

Batch2_students/Amol_Source/Assignment/JS_assignment/js_01_amol.js
=> Print Hello Amol

.gitignore, javascript_sessions/Js_Lectures/01_introduction.js
=> Siddhant admin source update

Batch2_students/Amol_Source/Assignment/JS_assignment/js_02_amol.js
Dear Siddhant, 
please check the today assignment 
which is completed in my assignment folder in please check and verify
=>  Assignment completed js_02_amol.js

Batch2_students/Atharva_source/Assignment/JS/js_02_Atharva.js
Raising PR for date 13.09.2024. Please refer the same.
=> js_02_Atharva.js

javascript_sessions/Js_Lectures/02_Datatypes_Numbers.js
=> PR_2 SIddhant

Batch2_students/adesh_source/assignment/assinment_js/js_01_adesh.js, Batch2_students/adesh_source/assignment/assinment_js/js_02_adesh.js, Batch2_students/adesh_source/notes/New Text Document.txt, Batch2_students/adesh_source/notes/practice.js
today's assinment merge the master,revised details.
=> today's assinment merge the master

Batch2_students/Ashutosh_Source/Assignment/JS_Assignment/js_02_Assignment.js
Pull request for second assignment of js
=> Second assignment of JS is completed

Batch2_students/Ashutosh_Source/Assignment/JS_Assignment/js_02_Assignment.js
=> Changes are done

Batch2_students/Ashutosh_Source/Assignment/JS_Assignment/js_03_Assignment.js
JS third assignment is completed.
Thanks and regards,
Ashutosh More
=> JS Assignment 3 

Batch2_students/Amol_Source/Assignment/JS_assignment/js_02_amol.js
Dear Siddhant,
Assignment no.JS_03_amol.js completed please check and merge..
=> assignment no Js_03_amol.js completed

Batch2_students/Shrinivas_source/Assignment/js_01_Shrinivas.js, Batch2_students/Shrinivas_source/Assignment/js_02_Shrinivas.js
I have completed first and second  assignment.  Please have look.
If you have any comments then please do let me know
=> asssignment

Batch2_students/Shrikant_Source/Assignment/js_assignment/js_03_Shrikant.js
Raising PR for Assignment, Please have a look
=> assignment update

Batch2_students/Shrinivas_source/Assignment/js_03_Shrinivas.js, Batch2_students/Shrinivas_source/Assignment/js_04_Shrinivas.js
i have completed third and fourth assignment. please have look.
=> Shrinivas source

Batch2_students/Atharva_source/Assignment/JS/Js_03_atharva.js, Batch2_students/Atharva_source/Assignment/JS/Js_04_atharva.js
raising PR for Assignment 3 , dated 18.09.2024 . Completed the assignment !.
=> Assignment 3

Batch2_students/Atharva_source/Assignment/JS/Js_05_atharva.js, Batch2_students/Atharva_source/Assignment/JS/Mock_02_assignment.js
=> Assignment 5 

Batch2_students/Amol_Source/Assignment/JS_assignment/Js_05_amol.js, Batch2_students/Amol_Source/Notes/Js_04_notes.txt, Batch2_students/Amol_Source/Notes/Js_05_notes.txt
Dear Siddhant ,
Assignment No 5 with nots are updated in branch. please have a look and merge.
=> Amol source. Assignment No. 05 ( Js_05_amol.js) completed

Batch2_students/Shrinivas_source/Assignment/js_05_Shrinivas.js
I have completed fifth assignment .please have a look.
=> js_05_Shrinivas.js

Batch2_students/Atharva_source/Assignment/JS/Js_05_atharva.js, Batch2_students/Atharva_source/Assignment/JS/Js_07_atharva.js, Batch2_students/Atharva_source/Assignment/JS/Js_08_atharva.js, Batch2_students/Atharva_source/Assignment/JS/Mock_02_assignment.js
, have some doubts about queries , will get it cleared tomorrow
=> Raising PR for Assigment 6 and 7

Batch2_students/Shrinivas_source/Assignment/js_05_Shrinivas.js, Batch2_students/Shrinivas_source/Assignment/js_07_Shrinivas.js, Batch2_students/Shrinivas_source/Assignment/js_08_Shrinivas.js
I have completed assignment. Please have a look.
If you have any comments then please do let me know.
=> assignment

Batch2_students/Shrikant_Source/Assignment/js_assignment/js_06_07_Shrikant.js, Batch2_students/Shrikant_Source/Assignment/js_assignment/js_08_Shrikant.js
Raising PR for Daily assignment, Please have a look and merge
=> Raising PR for assignment_06_07

Batch2_students/Shrikant_Source/Assignment/js_assignment/js_08_Shrikant.js, Batch2_students/Shrikant_Source/Assignment/js_assignment/js_09_Shrikant.js, javascript_sessions/Js_Assignments/js_09_assignment.js
Raising PR for assignment no-09, Please have a look
=> Raising PR for assignment

Batch2_students/Amol_Source/Assignment/JS_assignment/Js_08_amol.js, Batch2_students/Amol_Source/Assignment/JS_assignment/Js_09_amol.js, Batch2_students/Amol_Source/Assignment/JS_assignment/practice.js, Batch2_students/Amol_Source/Notes/Js_08_datenotes.txt
Hey Siddhant ,
Assignment No. Js_09_amol.js completed.
please check and merge..
=> Assignment No. Js_09_amol.js completed

Batch2_students/Amol_Source/Assignment/JS_assignment/Js_10_amol.js, Batch2_students/Amol_Source/Interview/interview question.txt, Batch2_students/Amol_Source/Queries/01_interviewNotes.txt
Dear Siddhant,
Assignment no.10 all question solve
please have a look and merge...
=> Assignment no.10 all question solve

Batch2_students/Shrinivas_source/Assignment/js_10_Shrinivas.js
I have completed assignment_10. Please have a look.
=> js_Shrinivas_10.js

Batch2_students/Shrinivas_source/Assignment/js_10_Shrinivas.js
I have completed assignment_10 .please have a look.
=> assignment_10

Batch2_students/Amol_Source/Assignment/JS_assignment/Js_10_amol.js
Dear Siddhant
" Question of palindrome and lonest word completed in Assignment no 10"
please check and approve...
=> Question of palindrome and lonest word completed in Assignment no 10

Batch2_students/Shrinivas_source/Assignment/js_07_Shrinivas.js, Batch2_students/Shrinivas_source/Assignment/js_08_Shrinivas.js, Batch2_students/Shrinivas_source/Assignment/js_10_Shrinivas.js, Batch2_students/Shrinivas_source/Assignment/js_12_Shrinivas.js
I have completed asiignment.please have a look.
=> js_12_Shrinivas.js

Batch2_students/Atharva_source/Assignment/JS/Js_10_atharva.js, Batch2_students/Atharva_source/Assignment/JS/Js_12_atharva.js
=> for Assignment  Js_12_atharva.js

Batch2_students/Ashutosh_Source/Assignment/JS_Assignment/js_10_Assignment.js, Batch2_students/Ashutosh_Source/Assignment/JS_Assignment/js_12_Assignment.js, Batch2_students/Ashutosh_Source/Notes/Notes.txt
Assignment 12 is added 
Regards,
Ashutosh More
=> assignment 12 is added

Batch2_students/Amol_Source/Assignment/JS_assignment/Js_11_amol.js, Batch2_students/Amol_Source/Assignment/JS_assignment/Js_12_amol.js
Hey Siddhant,
Assignment No .Js-12-amol.js completed
please check and merged..
=> Assignment No .Js-12-amol.js completed

Batch2_students/Atharva_source/Assignment/JS/Js_11_atharva.js, Batch2_students/Atharva_source/Assignment/JS/Js_12_atharva.js, Batch2_students/Atharva_source/Assignment/JS/Js_13_atharva.js
Raising PR for Assignment 12 , level 3 is in progress, will keep updating
=> Assignment 12

Batch2_students/Atharva_source/Assignment/JS/Js_12_atharva.js, Batch2_students/Atharva_source/Assignment/JS/Js_13_atharva.js, Batch2_students/Atharva_source/Assignment/JS/Js_14_atharva.js, Batch2_students/Atharva_source/Assignment/JS/Js_15_atharva.js, Batch2_students/Atharva_source/Assignment/JS/Js_16_atharva.js, Batch2_students/Atharva_source/notes/Domain_Solutions
Raising PR for assignment 16 !
=> Atharva source

Batch2_students/Amol_Source/Assignment/JS_assignment/Js_26_amol.js, Batch2_students/Amol_Source/Assignment/JS_assignment/practice.js, javascript_sessions/Js_Lectures/21_class.js, javascript_sessions/Js_Lectures/23_Promise.js, javascript_sessions/Js_Lectures/24_async_AND_Await.js, javascript_sessions/Js_Lectures/25_Closure.js, javascript_sessions/Js_Lectures/26_oops_inheritance.js
Dear Siddhant,
Inheritance Session updated.
please merge the PR
=> Inheritance Session updated

Playwright_Students/tests/Amol/Playwright_15_amol.spec.js, Playwright_Students/tests/Amol/Playwright_16_amol.spec.js, playwright/tests/16_Batch2_datepicker.spec.js
Dear Siddhant
PR raise for Assignment no 16 on Date picker (Playwright)
please have a look.
=> Assignment No.16 completed on Date Picker
